routes/web.php
<?php

use App\ArticleResource;
use App\Patiya;
use App\People;
use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Artisan;

Route::get("reboot",function (){
    Artisan::call("route:clear");
    Artisan::call("view:clear");
    Artisan::call("config:cache");
    Artisan::call("migrate");
    dd("Ready to use");
});
// last portfolio webpage
Route::get('/', function () {
    return view('website.portfolio');
});
// Route::get('/', function () {
//     return view('website.homePage');
// });

Route::get('/about', function () {
    return view('website.about');
});
Route::get('/artical-details', function () {
    return view('website.artical-details');
});

Route::get('/article', function () {
    return view('website.article');
});

Route::get('/resources', function () {
    return view('website.resource');
});


Route::get('/contact', function () {
    return view('website.contact');
});
Route::get('/hobbies', function () {
    return view('website.hobby');
})->name('website.hobby');


Route::get("/details-page/{id}",function ($id) {
    $article = ArticleResource::query()->findOrFail($id);
    return view('website.detail-page')->with(['article' => $article]);
})->name('detailsPage');

Auth::routes();

Route::middleware(['auth'])->group(function(){

    Route::view('home','home')->name('home');

    Route::get("/profile/edit/{id}",'HomeController@profileEdit')->name('profile.edit');
    Route::post("/profile/update/{id}",'HomeController@profileUpdate')->name('profile.update');
    Route::get("/change-password",'HomeController@changePassword')->name('profile.changePassword');
    Route::post("/updatePassword",'HomeController@updatePassword')->name('profile.updatePassword');
    Route::post("/frontEnd",'HomeController@images')->name('frontEnd.setting');

    Route::prefix("Skill")->name('skill.')->group(function (){
        $category = "SkillController@";
        Route::get('/',$category.'index')->name('add');
        Route::get('/edit/{id}',$category.'edit')->name('edit');
        Route::post('/store',$category.'store')->name('store');
        Route::post('/update/{id}',$category.'update')->name('update');
        Route::post('/destroy/{id}',$category.'destroy')->name('destroy');
        Route::get('/view',$category.'view')->name('view');
    });


    Route::prefix("category")->name('category.')->group(function (){
        $category = "CategoryController@";
        Route::get('/',$category.'index')->name('add');
        Route::get('/edit/{id}',$category.'edit')->name('edit');
        Route::post('/store',$category.'store')->name('store');
        Route::post('/update/{id}',$category.'update')->name('update');
        Route::post('/destroy/{id}',$category.'destroy')->name('destroy');
        Route::get('/view',$category.'view')->name('view');
    });

    Route::prefix("certification")->name('certification.')->group(function (){
        $certification = "CertificationController@";
        Route::get('/',$certification.'index')->name('add');
        Route::get('/edit/{id}',$certification.'edit')->name('edit');
        Route::post('/store',$certification.'store')->name('store');
        Route::post('/update/{id}',$certification.'update')->name('update');
        Route::post('/destroy/{id}',$certification.'destroy')->name('destroy');
        Route::get('/view',$certification.'view')->name('view');
    });


    Route::prefix("graduation")->name('graduation.')->group(function (){
        $graduation = "GraduationController@";
        Route::get('/',$graduation.'index')->name('add');
        Route::get('/edit/{id}',$graduation.'edit')->name('edit');
        Route::post('/store',$graduation.'store')->name('store');
        Route::post('/update/{id}',$graduation.'update')->name('update');
        Route::post('/destroy/{id}',$graduation.'destroy')->name('destroy');
        Route::get('/view',$graduation.'view')->name('view');
    });

    Route::prefix("experience")->name('experience.')->group(function (){
        $experience = "ExperienceController@";
        Route::get('/',$experience.'index')->name('add');
        Route::get('/edit/{id}',$experience.'edit')->name('edit');
        Route::post('/store',$experience.'store')->name('store');
        Route::post('/update/{id}',$experience.'update')->name('update');
        Route::post('/destroy/{id}',$experience.'destroy')->name('destroy');
    });

     Route::prefix("hobby")->name('hobby.')->group(function (){
        $hobby = "HobbyController@";
        Route::get('/',$hobby.'index')->name('add');
        Route::post('/store',$hobby.'store')->name('store');
        Route::get('/edit/{id}',$hobby.'edit')->name('edit');
        Route::post('/update/{id}',$hobby.'update')->name('update');
        Route::post('/destroy/{id}',$hobby.'destroy')->name('destroy');
    });

    Route::prefix("articleResource")->name('article.')->group(function (){
        $articleResource = "ArticleResourceController@";
        Route::get('/',$articleResource.'index')->name('add');
        Route::get('/edit/{id}',$articleResource.'edit')->name('edit');
        Route::post('/store',$articleResource.'store')->name('store');
        Route::post('/update/{id}',$articleResource.'update')->name('update');
        Route::post('/destroy/{id}',$articleResource.'destroy')->name('destroy');
        Route::get('/view',$articleResource.'view')->name('view');
    });

    /* Slider start */
    Route::prefix('Slider')->name('slider.')->group(function(){
        $slider = 'SliderController@';
        Route::get('/view',$slider.'index')->name('add');
        Route::get('/resources',$slider.'viewResource')->name('view');
        Route::get('/edit/{id}',$slider.'edit')->name('edit');
        Route::post('/store-archive',$slider.'store')->name('store');
        Route::post('/update-archive/{id}',$slider.'update')->name('update');
        Route::post('/delete-archive/{id}',$slider.'destroy')->name('destroy');
        Route::post('/download-archive/{id}',$slider.'download')->name('download');
    });
    /* Slider end */

});

resources/views/article/articles.blade.php
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>SL</th>
                <th>Author</th>
                <th>Publisher</th>
                <th>Year</th>
                <th>DOI</th>
                <th>Category</th>
                <th>Title</th>
                <th>Body</th>
                <th>is Article?</th>
                <th>Image Files</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @forelse(Articles() as $key=>$article_list)
            <tr>
                <td> {{ $loop->iteration }}</td>
                <td>{{ $article_list->author }}</td>
                <td>{{ $article_list->publisher }}</td>
                <td>{{ $article_list->year }}</td>
                <td>{{ $article_list->doi }}</td>
                <td>{{ $article_list->category->name }}</td>
                <td>{{ $article_list->title }}</td>
                <td>{{ $article_list->body }}</td>
                <td>
                    @if($article_list->isArticle ==1 )
                    <button class="btn btn-info"> Article</button>
                    @else
                    <button class="btn btn-primary"> Resource</button>
                    @endif
                </td>
                <td>
                    @forelse ($article_list->files as $key=>$file)
                    <a href="{{ asset('project_files/articleResource/'.$file->name) }}" target="_blank">
                        <img src="{{ asset('project_files/articleResource/'.$file->name) }}" height="70" width="70"
                            alt="">
                    </a>
                    @empty

                    @endforelse
                </td>
                <td>
                    @if(isset($article) && $article->id == $article_list->id)
                    <a href="#" class="badge badge-rounded badge-success">Updating....</a>
                    @else
                    <a href="{{ route('article.edit',$article_list->id) }}" class="btn-success btn btn-sm"> <i
                            class="fa fa-edit "></i> </a>
                    {{ Form::open(['route'=>['article.destroy',$article_list->id],"method"=>'post',"class"=>"destroyForm"]) }}
                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')"> <i
                            class="fa fa-trash"></i> </button>
                    {{ Form::close() }}
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="8">No Article Found</td>
            </tr>
            @endforelse
        </tbody>
    </table>
</div>

resources/views/article/edit-article.blade.php
@extends('layouts.admin')

@section('title','Update Article : '.$article->name)

@section('content')
<div class="page-titles">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:void(0)">Article</a></li>
        <li class="breadcrumb-item active"><a href="javascript:void(0)">Update {{ $article->name }} Profile</a></li>
    </ol>
</div>

<div class="row">
    {{-- Article Form Start --}}
    <div class="col-xl-12 col-lg-12 col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Update Form</h4>
            </div>
            <div class="card-body">
                <div class="basic-form">
                    {{ Form::model($article,['route'=>['article.update',$article->id],'method'=>"post",'files'=>true]) }}
                    @include('article.form-article',["button"=>"Update Article"])
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
    {{-- Article Form End --}}

    {{-- Article Lists Start --}}
    <div class="col-xl-12 col-lg-12 col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Articles</h4>
            </div>
            <div class="card-body">
                @include('article.articles')
            </div>
        </div>
    </div>
    {{-- Article Lists End --}}

</div>

@endsection


@section('js')
<script>
$(document).on("click", ".changeStatus", function() {
    return confirm("Are you sure to change status?");
});
</script>

@endsection

resources/views/article/form-article.blade.php
<div class="row">

    <div class="col-lg-3">
        <div class="form-group">
            <label>Author*</label>
            {{ Form::text('author',null,['class'=>'form-control','placeholder'=>'Ex. Linkhon Chy','required']) }}
        </div>
    </div>

    <div class="col-lg-3">
        <div class="form-group">
            <label>Publisher.*</label>
            {{ Form::text('publisher',null,['class'=>'form-control','placeholder'=>'Ex. Google Publisher','required']) }}
        </div>
    </div>

    <div class="col-lg-3">
        <div class="form-group">
            <label>Year.*</label>
            {{ Form::text('year',null,['class'=>'form-control','placeholder'=>'Ex. '.Date('Y')]) }}
        </div>
    </div>

    <div class="col-lg-3">
        <div class="form-group">
            <label>DOI.*</label>
            {{ Form::text('doi',null,['class'=>'form-control','placeholder'=>'Ex. '.rand(1111,9999),'required']) }}
        </div>
    </div>
    <div class="col-lg-3">
        <div class="form-group">
            <label>Select Category</label>
            {{ Form::select('category_id',category_pluck(),isset($article) ? $article->category_id : false,['class'=>'form-control','required']) }}
        </div>
    </div>


    <div class="col-lg-3">
        <div class="form-group">
            <label>Article/Resource Title.*</label>
            {{ Form::text('title',null,['class'=>'form-control','placeholder'=>'Ex. Big Data Handling....','required']) }}
        </div>
    </div>

    <div class="col-lg-3">
        <div class="form-group">
            <label>Article/Resource Date & Time.*</label>
            {{ Form::date('datetime',null,['class'=>'form-control','required']) }}
        </div>
    </div>


    <div class="col-lg-3">
        <div class="form-group">
            <label>Select Is Article/Resource</label>
            {{ Form::select('isArticle',['1'=>'Article', '2'=>'Resource'],true,['class'=>'form-control','required']) }}
        </div>
    </div>



    <div class="col-lg-9">
        <div class="form-group">
            <label>Article/Resource Description.</label>
            {{ Form::textarea( 'body',null,['class'=>'form-control','placeholder'=>'Ex. Article/Resource Details']) }}
        </div>
    </div>


    <div class="col-lg-3">
        <div class="form-group">
            <label>Article/Resources Image Files.</label>
            {{ Form::file( 'images[]',['class'=>'form-control','access'=>'images/*','multiple']) }}
        </div>
    </div>


    <div class="col-lg-3">
        <div class="form-group ">
            {{ Form::submit($button,['class'=>'btn btn-block btn-success']) }}
        </div>
    </div>

</div>

resources/views/article/index.blade.php
@extends('layouts.admin')

@section('title','New Article')

@section('content')
<div class="page-titles">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:void(0)">Article</a></li>
        <li class="breadcrumb-item active"><a href="javascript:void(0)">New Article</a></li>
    </ol>
</div>

<div class="row">
    {{-- Article Form Start --}}
    <div class="col-xl-12 col-lg-12 col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Article Form</h4>
            </div>
            <div class="card-body">
                <div class="basic-form">
                    {{ Form::open(['route'=>'article.store','method'=>"post",'files'=>true]) }}
                    @include('article.form-article',["button"=>"Save Article/Resource"])
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
    {{-- Article Form End --}}

    {{-- Article Lists Start --}}
    <div class="col-xl-12 col-lg-12 col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Articles</h4>
            </div>
            <div class="card-body">
                @include('article.articles')
            </div>
        </div>
    </div>
    {{-- Article Lists End --}}

</div>

@endsection


@section('js')
<script>
$(document).on("click", ".changeStatus", function() {
    return confirm("Are you sure to change status?");
});
</script>

@endsection