routes/web.php
<?php

use App\ArticleResource;
use App\Patiya;
use App\People;
use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Artisan;

Route::get("reboot",function (){
    Artisan::call("route:clear");
    Artisan::call("view:clear");
    Artisan::call("config:cache");
    Artisan::call("migrate");
    dd("Ready to use");
});
// last portfolio webpage
Route::get('/', function () {
    return view('website.portfolio');
});
// Route::get('/', function () {
//     return view('website.homePage');
// });

Route::get('/about', function () {
    return view('website.about');
});
Route::get('/artical-details', function () {
    return view('website.artical-details');
});

Route::get('/article', function () {
    return view('website.article');
});

Route::get('/resources', function () {
    return view('website.resource');
});


Route::get('/contact', function () {
    return view('website.contact');
});
Route::get('/hobbies', function () {
    return view('website.hobby');
})->name('website.hobby');


Route::get("/details-page/{id}",function ($id) {
    $article = ArticleResource::query()->findOrFail($id);
    return view('website.detail-page')->with(['article' => $article]);
})->name('detailsPage');

Auth::routes();

Route::middleware(['auth'])->group(function(){

    Route::view('home','home')->name('home');

    Route::get("/profile/edit/{id}",'HomeController@profileEdit')->name('profile.edit');
    Route::post("/profile/update/{id}",'HomeController@profileUpdate')->name('profile.update');
    Route::get("/change-password",'HomeController@changePassword')->name('profile.changePassword');
    Route::post("/updatePassword",'HomeController@updatePassword')->name('profile.updatePassword');
    Route::post("/frontEnd",'HomeController@images')->name('frontEnd.setting');

    Route::prefix("Skill")->name('skill.')->group(function (){
        $category = "SkillController@";
        Route::get('/',$category.'index')->name('add');
        Route::get('/edit/{id}',$category.'edit')->name('edit');
        Route::post('/store',$category.'store')->name('store');
        Route::post('/update/{id}',$category.'update')->name('update');
        Route::post('/destroy/{id}',$category.'destroy')->name('destroy');
        Route::get('/view',$category.'view')->name('view');
    });


    Route::prefix("category")->name('category.')->group(function (){
        $category = "CategoryController@";
        Route::get('/',$category.'index')->name('add');
        Route::get('/edit/{id}',$category.'edit')->name('edit');
        Route::post('/store',$category.'store')->name('store');
        Route::post('/update/{id}',$category.'update')->name('update');
        Route::post('/destroy/{id}',$category.'destroy')->name('destroy');
        Route::get('/view',$category.'view')->name('view');
    });

    Route::prefix("certification")->name('certification.')->group(function (){
        $certification = "CertificationController@";
        Route::get('/',$certification.'index')->name('add');
        Route::get('/edit/{id}',$certification.'edit')->name('edit');
        Route::post('/store',$certification.'store')->name('store');
        Route::post('/update/{id}',$certification.'update')->name('update');
        Route::post('/destroy/{id}',$certification.'destroy')->name('destroy');
        Route::get('/view',$certification.'view')->name('view');
    });


    Route::prefix("graduation")->name('graduation.')->group(function (){
        $graduation = "GraduationController@";
        Route::get('/',$graduation.'index')->name('add');
        Route::get('/edit/{id}',$graduation.'edit')->name('edit');
        Route::post('/store',$graduation.'store')->name('store');
        Route::post('/update/{id}',$graduation.'update')->name('update');
        Route::post('/destroy/{id}',$graduation.'destroy')->name('destroy');
        Route::get('/view',$graduation.'view')->name('view');
    });

    Route::prefix("experience")->name('experience.')->group(function (){
        $experience = "ExperienceController@";
        Route::get('/',$experience.'index')->name('add');
        Route::get('/edit/{id}',$experience.'edit')->name('edit');
        Route::post('/store',$experience.'store')->name('store');
        Route::post('/update/{id}',$experience.'update')->name('update');
        Route::post('/destroy/{id}',$experience.'destroy')->name('destroy');
    });

     Route::prefix("hobby")->name('hobby.')->group(function (){
        $hobby = "HobbyController@";
        Route::get('/',$hobby.'index')->name('add');
        Route::post('/store',$hobby.'store')->name('store');
        Route::get('/edit/{id}',$hobby.'edit')->name('edit');
        Route::post('/update/{id}',$hobby.'update')->name('update');
        Route::post('/destroy/{id}',$hobby.'destroy')->name('destroy');
    });

    Route::prefix("articleResource")->name('article.')->group(function (){
        $articleResource = "ArticleResourceController@";
        Route::get('/',$articleResource.'index')->name('add');
        Route::get('/edit/{id}',$articleResource.'edit')->name('edit');
        Route::post('/store',$articleResource.'store')->name('store');
        Route::post('/update/{id}',$articleResource.'update')->name('update');
        Route::post('/destroy/{id}',$articleResource.'destroy')->name('destroy');
        Route::get('/view',$articleResource.'view')->name('view');
    });

    /* Slider start */
    Route::prefix('Slider')->name('slider.')->group(function(){
        $slider = 'SliderController@';
        Route::get('/view',$slider.'index')->name('add');
        Route::get('/resources',$slider.'viewResource')->name('view');
        Route::get('/edit/{id}',$slider.'edit')->name('edit');
        Route::post('/store-archive',$slider.'store')->name('store');
        Route::post('/update-archive/{id}',$slider.'update')->name('update');
        Route::post('/delete-archive/{id}',$slider.'destroy')->name('destroy');
        Route::post('/download-archive/{id}',$slider.'download')->name('download');
    });
    /* Slider end */

});

resources/views/includes/admin-home.blade.php
    <div class="col-xl-4 col-xxl-4 col-sm-4">
        <div class="card grd-card">
            <div class="card-body">
                <div class="media align-items-center">
                    <div class="media-body mr-2">
                        <h2 class="text-white font-w600"> {{ 0 }} </h2>

                        <span class="text-white"> Total Book </span>
                    </div>
                    <div class="d-inline-block position-relative donut-chart-sale">
                        <span class="donut1"
                            data-peity="{ &quot;fill&quot;: [&quot;rgb(255, 255, 255)&quot;, &quot;rgba(255, 255, 255, 0)&quot;],   &quot;innerRadius&quot;: 41, &quot;radius&quot;: 10}"
                            style="display: none;">6/8</span><svg class="peity" height="92" width="92">
                            <path d="M 46 0 A 46 46 0 1 1 0 46.00000000000001 L 5 46.00000000000001 A 41 41 0 1 0 46 5"
                                data-value="6" fill="rgb(255, 255, 255)"></path>
                            <path
                                d="M 0 46.00000000000001 A 46 46 0 0 1 45.99999999999999 0 L 45.99999999999999 5 A 41 41 0 0 0 5 46.00000000000001"
                                data-value="2" fill="rgba(255, 255, 255, 0)"></path>
                        </svg>
                        <small class="text-primary">
                            <i class="fa fa-book fa-2x"></i>
                        </small>
                        <span class="circle bg-white"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-xl-4 col-xxl-4 col-sm-4">
        <div class="card grd-card">
            <div class="card-body">
                <div class="media align-items-center">
                    <div class="media-body mr-2">
                        <h2 class="text-white font-w600">{{   0 }}</h2>
                        <span class="text-white">Total Students </span>
                    </div>
                    <div class="d-inline-block position-relative donut-chart-sale">
                        <span class="donut1"
                            data-peity="{ &quot;fill&quot;: [&quot;rgb(255, 255, 255)&quot;, &quot;rgba(255, 255, 255, 0)&quot;],   &quot;innerRadius&quot;: 41, &quot;radius&quot;: 10}"
                            style="display: none;">6/8</span><svg class="peity" height="92" width="92">
                            <path d="M 46 0 A 46 46 0 1 1 0 46.00000000000001 L 5 46.00000000000001 A 41 41 0 1 0 46 5"
                                data-value="6" fill="rgb(255, 255, 255)"></path>
                            <path
                                d="M 0 46.00000000000001 A 46 46 0 0 1 45.99999999999999 0 L 45.99999999999999 5 A 41 41 0 0 0 5 46.00000000000001"
                                data-value="2" fill="rgba(255, 255, 255, 0)"></path>
                        </svg>

                        <small class="text-primary">
                            <i class="fa fa-users fa-2x"></i>
                        </small>

                        <span class="circle bg-white"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-4 col-xxl-4 col-sm-4">
        <div class="card grd-card">
            <div class="card-body">
                <div class="media align-items-center">
                    <div class="media-body mr-2">
                        <h2 class="text-white font-w600">{{  0 }}</h2>
                        <span class="text-white"> Returnable Book </span>
                    </div>
                    <div class="d-inline-block position-relative donut-chart-sale">
                        <span class="donut1"
                            data-peity="{ &quot;fill&quot;: [&quot;rgb(255, 255, 255)&quot;, &quot;rgba(255, 255, 255, 0)&quot;],   &quot;innerRadius&quot;: 41, &quot;radius&quot;: 10}"
                            style="display: none;">6/8</span><svg class="peity" height="92" width="92">
                            <path d="M 46 0 A 46 46 0 1 1 0 46.00000000000001 L 5 46.00000000000001 A 41 41 0 1 0 46 5"
                                data-value="6" fill="rgb(255, 255, 255)"></path>
                            <path
                                d="M 0 46.00000000000001 A 46 46 0 0 1 45.99999999999999 0 L 45.99999999999999 5 A 41 41 0 0 0 5 46.00000000000001"
                                data-value="2" fill="rgba(255, 255, 255, 0)"></path>
                        </svg>
                        <small class="text-primary">
                            <i class="fa fa-bookmark-o fa-2x"></i>
                        </small>
                        <span class="circle bg-white"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>

resources/views/includes/admin-left-sidebar.blade.php
<li>
    <a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
        <i class="fa fa-file-pdf-o"></i>
        <span class="nav-text">Manage Profile</span>
    </a>
    <ul aria-expanded="false">
        <li><a href="{{ route('profile.edit',1) }}"> Update Profile</a></li>
        <li><a href="{{ route('profile.changePassword') }}"> Change Password</a></li>
    </ul>
</li>

<li>
    <a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
        <i class=" fa fa-cogs"></i>
        <span class="nav-text">Manage Settings</span>
    </a>
    <ul aria-expanded="false">
        <li><a href="{{ route('skill.add') }}">Skill Manage</a></li>
        <li><a href="{{ route('category.add') }}">Article/Resource Category</a></li>
        <li><a href="{{ route('certification.add') }}">Certification Category</a> </li>
        <li><a href="{{ route('frontEnd.setting') }}">Front-End Setting</a> </li>
    </ul>
</li>

<li>
    <a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
        <i class="fa fa-book"></i>
        <span class="nav-text">Manage Graduation</span>
    </a>
    <ul aria-expanded="false">
        <li><a href="{{ route('graduation.add') }}">Graduation Add/Update</a></li>
    </ul>
</li>


<li>
    <a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
        <i class="fa fa-book"></i>
        <span class="nav-text">Manage Experience</span>
    </a>
    <ul aria-expanded="false">
        <li><a href="{{ route('experience.add') }}">Experience Add/Update</a></li>
    </ul>
</li>


<li>
    <a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
        <i class="fa fa-book"></i>
        <span class="nav-text">Manage Hobby</span>
    </a>
    <ul aria-expanded="false">
        <li><a href="{{ route('hobby.add') }}">Hobby Add/Update</a></li>
    </ul>
</li>


<li>
    <a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
        <i class="fa fa-book"></i>
        <span class="nav-text">Manage Article/Resource</span>
    </a>
    <ul aria-expanded="false">
        <li><a href="{{ route('article.add') }}">Article/Resource Add/Update</a></li>
    </ul>
</li>

resources/views/includes/admin-menu.blade.php
<div class="deznav">
    @php
    $name = Route::currentRouteName();
    @endphp
    <div class="deznav-scroll">
        <ul class="metismenu" id="menu">
            <li>
                <a class=" ai-icon" href="{{ $name != 'home' ? route('home') : 'javascript:void()' }} "
                    aria-expanded="false">
                    <i class="flaticon-381-networking"></i>
                    <span class="nav-text">Dashboard</span>
                </a>
            </li>

            @include('includes.admin-left-sidebar')


            <li>
                <a href="#" role="button" onclick="document.getElementById('logout').submit()" aria-expanded="false"
                    class="ai-icon">
                    <i class="fa fa-sign-out"></i>
                    <span class="nav-text">Logout</span>
                    <form action="{{ route('logout') }}" method="post" id="logout">
                        @csrf
                    </form>
                </a>
            </li>


        </ul>

        <div class="copyright">
            <p><strong>Portfolio v.1 Application</strong> © {{ Date('Y') }} All Rights Reserved</p>
            <p>Made with <i class="fa fa-heart"></i> by Linkhon Chowdhury</p>
        </div>
    </div>
</div>

resources/views/includes/footer-script.blade.php
<!--**********************************
        Scripts
***********************************-->
<!-- Required vendors -->
<script src="{{ asset('template/vendor/global/global.min.js') }}"></script>
@yield('calendar')

<script src="{{ asset('template/vendor/bootstrap-select/dist/js/bootstrap-select.min.js') }}"></script>

{{-- Datatable start --}}
<link rel="stylesheet" href="{{ asset('template/vendor/datatables/css/jquery.dataTables.min.css') }}"> </link>
<script src="{{ asset('template/vendor/datatables/js/jquery.dataTables.min.js') }}"></script>
{{-- Datatable end --}}

<script src="{{ asset('template/js/custom.min.js') }}"></script>
<script src="{{ asset('template/js/deznav-init.js') }}"></script>

<!-- Chart piety plugin files -->
<script src="{{ asset('template/vendor/peity/jquery.peity.min.js') }}"></script>

<!-- Dashboard 1 -->
@if(Route::currentRouteName() == 'home')
@endif

<!-- Toastr -->
<script src="{{ asset('template/vendor/toastr/js/toastr.min.js')}}"></script>

<!-- All init script -->
<script src="{{ asset('template/js/plugins-init/toastr-init.js')}}"></script>

resources/views/includes/footer.blade.php
<?php

resources/views/includes/header-script.blade.php
<link rel="icon" type="image/png" sizes="16x16" href="./images/favicon.png">
<link rel="stylesheet" href="{{ asset('template/vendor/chartist/css/chartist.min.css') }}">
<link rel="stylesheet" href="{{ asset('template/vendor/toastr/css/toastr.min.css') }}">
<link href="{{ asset('template/vendor/bootstrap-select/dist/css/bootstrap-select.min.css') }}" rel="stylesheet">
<link href="{{ asset('template/css/style.css') }}" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">

resources/views/includes/header.blade.php
<!--**********************************
            Nav header start
***********************************-->
<div class="nav-header">
    <a href="{{ route("home") }}" class="brand-logo">
        <img class="logo-abbr" src="{{ asset('template/logo.png') }}" alt="">
{{--        <img class="brand-title" src="{{ asset('logo/clhg.png') }}" alt="">--}}
    </a>

    <div class="nav-control">
        <div class="hamburger">
            <span class="line"></span><span class="line"></span><span class="line"></span>
        </div>
    </div>
</div>
<!--**********************************
    Nav header end
***********************************-->

<!--**********************************
    Chat box start
***********************************-->

{{--@include('includes.chatbox')--}}

<!--**********************************
    Chat box End
***********************************-->

<!--**********************************
    Header start
***********************************-->
<div class="header">
    <div class="header-content">
        <nav class="navbar navbar-expand">
            <div class="collapse navbar-collapse justify-content-between">
                <div class="header-left">
                    <div class="dashboard_bar">
                        Dashboard
                        <span>Welcome to EDU Library Mang.</span>
                    </div>
                </div>

                <ul class="navbar-nav header-right">

                    @include('includes.gift')

                    <li class="nav-item dropdown header-profile">
                        <a class="nav-link" href="javascript:void(0)" role="button" data-toggle="dropdown">
                            <img src="{{ asset('template/logo.png') }}" width="20" alt=""/>
                            <div class="header-info">
                                <span class="text-black"><strong>{{ auth()->user()->name}}</strong></span>
                                <p class="fs-12 mb-0" style="background: maroon;color: white;padding:5px; border-radius: 10px;text-align: center">{{ auth()->user()->isAdmin == 1 ? 'Logged in as Admin ' : 'Logged in as Student ' }} </p>
                            </div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">


                            <a href="#" class="dropdown-item ai-icon">
                                <svg id="icon-user1" xmlns="http://www.w3.org/2000/svg" class="text-primary" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                <span class="ml-2">

                                    Profile Coming soon..</span>
                            </a>
                            <a href="#" class="dropdown-item ai-icon">
                                <svg id="icon-inbox" xmlns="http://www.w3.org/2000/svg" class="text-success" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
                                <span class="ml-2">Inbox Coming soon.. </span>
                            </a>

                            @if(session('impersonated_by'))
                                <a href="{{ route('user.leaveImpersonate') }}"  class="dropdown-item ai-icon">
                                    <svg id="icon-logout" xmlns="http://www.w3.org/2000/svg" class="text-danger" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
                                    <span class="ml-2"> Leave Impersonation</span>
                                </a>
                            @else
                                <a href="#" role="button" onclick="document.getElementById('logout').submit()" class="dropdown-item ai-icon">
                                    <svg id="icon-logout" xmlns="http://www.w3.org/2000/svg" class="text-danger" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>

                                    <span class="ml-2"> Logout </span>
                                    <form action="{{ route('logout') }}" method="post" id="logout">
                                        @csrf
                                    </form>
                                </a>
                            @endif

{{--                            --}}
{{--                            <a href="./page-login.html" class="dropdown-item ai-icon">--}}
{{--                                <svg id="icon-logout" xmlns="http://www.w3.org/2000/svg" class="text-danger" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>--}}
{{--                                <span class="ml-2">Logout </span>--}}
{{--                            </a>--}}

                        </div>
                    </li>

                </ul>
            </div>
        </nav>
    </div>
</div>
<!--**********************************
    Header end ti-comment-alt
***********************************-->

resources/views/includes/messages.blade.php
<?php

resources/views/includes/notification.blade.php
<li class="nav-item dropdown notification_dropdown">
    <a class="nav-link  ai-icon" href="javascript:void(0)" role="button" data-toggle="dropdown">
        <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M22.75 15.8385V13.0463C22.7471 10.8855 21.9385 8.80353 20.4821 7.20735C19.0258 5.61116 17.0264 4.61555 14.875 4.41516V2.625C14.875 2.39294 14.7828 2.17038 14.6187 2.00628C14.4546 1.84219 14.2321 1.75 14 1.75C13.7679 1.75 13.5454 1.84219 13.3813 2.00628C13.2172 2.17038 13.125 2.39294 13.125 2.625V4.41534C10.9736 4.61572 8.97429 5.61131 7.51794 7.20746C6.06159 8.80361 5.25291 10.8855 5.25 13.0463V15.8383C4.26257 16.0412 3.37529 16.5784 2.73774 17.3593C2.10019 18.1401 1.75134 19.1169 1.75 20.125C1.75076 20.821 2.02757 21.4882 2.51969 21.9803C3.01181 22.4724 3.67904 22.7492 4.375 22.75H9.71346C9.91521 23.738 10.452 24.6259 11.2331 25.2636C12.0142 25.9013 12.9916 26.2497 14 26.2497C15.0084 26.2497 15.9858 25.9013 16.7669 25.2636C17.548 24.6259 18.0848 23.738 18.2865 22.75H23.625C24.321 22.7492 24.9882 22.4724 25.4803 21.9803C25.9724 21.4882 26.2492 20.821 26.25 20.125C26.2486 19.117 25.8998 18.1402 25.2622 17.3594C24.6247 16.5786 23.7374 16.0414 22.75 15.8385ZM7 13.0463C7.00232 11.2113 7.73226 9.45223 9.02974 8.15474C10.3272 6.85726 12.0863 6.12732 13.9212 6.125H14.0788C15.9137 6.12732 17.6728 6.85726 18.9703 8.15474C20.2677 9.45223 20.9977 11.2113 21 13.0463V15.75H7V13.0463ZM14 24.5C13.4589 24.4983 12.9316 24.3292 12.4905 24.0159C12.0493 23.7026 11.716 23.2604 11.5363 22.75H16.4637C16.284 23.2604 15.9507 23.7026 15.5095 24.0159C15.0684 24.3292 14.5411 24.4983 14 24.5ZM23.625 21H4.375C4.14298 20.9999 3.9205 20.9076 3.75644 20.7436C3.59237 20.5795 3.50014 20.357 3.5 20.125C3.50076 19.429 3.77757 18.7618 4.26969 18.2697C4.76181 17.7776 5.42904 17.5008 6.125 17.5H21.875C22.571 17.5008 23.2382 17.7776 23.7303 18.2697C24.2224 18.7618 24.4992 19.429 24.5 20.125C24.4999 20.357 24.4076 20.5795 24.2436 20.7436C24.0795 20.9076 23.857 20.9999 23.625 21Z" fill="#4C8147"/>
        </svg>
        <span class="badge light text-white bg-primary rounded-circle">12</span>
    </a>
    <div class="dropdown-menu rounded dropdown-menu-right">
        <div id="DZ_W_Notification1" class="widget-media dz-scroll p-3 height380">
            <ul class="timeline">
                <li>
                    <div class="timeline-panel">
                        <div class="media mr-2">
                            <img alt="image" width="50" src="images/avatar/1.jpg">
                        </div>
                        <div class="media-body">
                            <h6 class="mb-1">Dr sultads Send you Photo</h6>
                            <small class="d-block">29 July 2020 - 02:26 PM</small>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="timeline-panel">
                        <div class="media mr-2 media-info">
                            KG
                        </div>
                        <div class="media-body">
                            <h6 class="mb-1">Resport created successfully</h6>
                            <small class="d-block">29 July 2020 - 02:26 PM</small>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="timeline-panel">
                        <div class="media mr-2 media-success">
                            <i class="fa fa-home"></i>
                        </div>
                        <div class="media-body">
                            <h6 class="mb-1">Reminder : Treatment Time!</h6>
                            <small class="d-block">29 July 2020 - 02:26 PM</small>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="timeline-panel">
                        <div class="media mr-2">
                            <img alt="image" width="50" src="images/avatar/1.jpg">
                        </div>
                        <div class="media-body">
                            <h6 class="mb-1">Dr sultads Send you Photo</h6>
                            <small class="d-block">29 July 2020 - 02:26 PM</small>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="timeline-panel">
                        <div class="media mr-2 media-danger">
                            KG
                        </div>
                        <div class="media-body">
                            <h6 class="mb-1">Resport created successfully</h6>
                            <small class="d-block">29 July 2020 - 02:26 PM</small>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="timeline-panel">
                        <div class="media mr-2 media-primary">
                            <i class="fa fa-home"></i>
                        </div>
                        <div class="media-body">
                            <h6 class="mb-1">Reminder : Treatment Time!</h6>
                            <small class="d-block">29 July 2020 - 02:26 PM</small>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <a class="all-notification" href="javascript:void(0)">See all notifications <i class="ti-arrow-right"></i></a>
    </div>
</li>